#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("front-end-path-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function (line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log("palindrome detected:", line);

    fs.writeFile("./palindromes.txt", line + "\n", { flag: "a+" }, (err) => {
      if (err) {
        console.error(err);
      }
    });
  }
});
