#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
//
const { request } = require("urllib");
let url = process.argv[2];
const is_url_present = !!url;

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

if (!is_url_present) {
  console.log("No URL provided");
  process.exit(1);
}

request(url, { followRedirect: true })
  .then(({ data, res }) => {
    console.log("statusCode: " + res.statusCode);
    console.log("Headers:" + res.headers);

    let body = data.toString();

    // Simulate a Document Object Model
    let { document } = new JSDOM(body).window;

    // Grab all the paragraphs and references.
    let paragraphs = document.querySelectorAll("p");
    let references = document.querySelectorAll(".reference");

    references.forEach(function (reference) {
      reference.remove();
    });

    paragraphs.forEach(function (paragraph) {
      console.log(paragraph.textContent);
    });
  })
  .catch((err) => {
    console.log(err);
  });

console.log("print all arguments to script:");
process.argv.forEach((arg) => console.log(arg));
